version: "3.7"
services:
  mysql:
    build: ./mysql
    container_name: paythere_mysql
    restart: always
    ports:
      - '3000:3306'
    environment:
      - TZ=Asia/Seoul

  paythere_back:
    build: ./app
    container_name: paythere_back
    depends_on: 
      - mysql
    restart: always
    ports:
      - "0.0.0.0:5001:5001"

